# Generated by Django 5.1.7 on 2025-03-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Elf'), (2, 'Wizard'), (3, 'Dwarf')]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Sword'), (2, 'Staff'), (3, 'Axe')]),
        ),
    ]
