# Generated by Django 5.1.7 on 2025-03-15 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_alter_tradeoffer_status_alter_user_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weapon',
            name='variant',
        ),
        migrations.CreateModel(
            name='WeaponVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=20)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='trading.weapon')),
            ],
        ),
        migrations.AddField(
            model_name='ledger',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.weaponvariant'),
        ),
        migrations.AddField(
            model_name='tradeitem',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.weaponvariant'),
        ),
    ]
