# Generated by Django 5.1.7 on 2025-03-17 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_remove_weapon_variant_weaponvariant_ledger_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.weaponvariant'),
        ),
    ]
