# Generated by Django 5.1.7 on 2025-03-18 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_inventory_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradeoffer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
